role: as
UA: 1062345
port: 8081
debug: 1
ipv6_address: 2001:da8:a012:389:7bf3:43b7:9c07:4f06
init_fl_freq: 1110.0
init_rl_freq: 964.0
http:
  http_port: 10623
  auto_auth: 1
path:
  start-longitude: 117.3334
  start-latitude: 37.8129
  refer-longitude: 117.05
  refer-latitude: 33.4
AS-SAC: 306
GS-SAC: 16

