role: as
UA: 1382345
port: 8081
debug: 1
ipv6_address: 2001:da8:a012:389:7bf3:43b7:9c07:4f38
init_fl_freq: 1110.0
init_rl_freq: 964.0
http:
  http_port: 13823
  auto_auth: 1
path:
  start-longitude: 115.8179
  start-latitude: 35.6
  refer-longitude: 117.05
  refer-latitude: 33.4
AS-SAC: 338
GS-SAC: 16

