role: as
UA: 1192345
port: 8081
debug: 1
ipv6_address: 2001:da8:a012:389:7bf3:43b7:9c07:4f19
init_fl_freq: 1110.0
init_rl_freq: 964.0
http:
  http_port: 11923
  auto_auth: 1
path:
  start-longitude: 116.5824
  start-latitude: 38.0071
  refer-longitude: 117.05
  refer-latitude: 33.4
AS-SAC: 319
GS-SAC: 16

