role: as
UA: 1122345
port: 8081
debug: 1
ipv6_address: 2001:da8:a012:389:7bf3:43b7:9c07:4f12
init_fl_freq: 1110.0
init_rl_freq: 964.0
http:
  http_port: 11223
  auto_auth: 1
path:
  start-longitude: 115.9956
  start-latitude: 36.6546
  refer-longitude: 117.05
  refer-latitude: 33.4
AS-SAC: 312
GS-SAC: 16

